FOREX_PAIRS = {
    "USDCHF=X": "USD/CHF",
    "USDJPY=X": "USD/JPY",
    "USDCAD=X": "USD/CAD",
    "NZDUSD=X": "NZD/USD",
    "AUDUSD=X": "AUD/USD",
    "EURUSD=X": "EUR/USD",
    "GBPUSD=X": "GBP/USD",
}

# Пипс размер для разных типов пар
PIP_SIZE = {
    "USDJPY=X": 0.01,
    "EURJPY=X": 0.01,
    "GBPJPY=X": 0.01,
    "AUDJPY=X": 0.01,
    "NZDJPY=X": 0.01,
    "CADJPY=X": 0.01,
    "CHFJPY=X": 0.01,
    # Все остальные пары: 0.0001
}
DEFAULT_PIP_SIZE = 0.0001

TIMEFRAME = "15m"
ANALYSIS_INTERVAL_MINUTES = 15
SMA_SHORT = 10
SMA_LONG = 30
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

ALERT_COOLDOWN_SECONDS = 3600

TRADER_INITIAL_BALANCE = 10000.0
TRADER_RISK_PER_TRADE = 0.02
TRADER_MAX_POSITIONS = 3
TRADER_MAX_DRAWDOWN_PCT = 0.15
TRADER_MIN_SIGNAL_STRENGTH = 3
TRADER_TRAILING_STOP_ACTIVATION = 0.003
TRADER_TRAILING_STOP_DISTANCE = 0.002

# LLM Settings
LLM_ENABLED = True
MISTRAL_API_KEY = "bFeUpGxuKqbph0CDDxyqr8hyXbNI2Bhm"
ZHIPU_API_KEY = "a3ae635f86124712a55039f9c32eeabd.8qWHHNn7NrnG2XuA"
OPENROUTER_API_KEY = ""

# Fallback: if LLM fails, use rule-based analysis
LLM_FALLBACK = True
